// src/components/AiSummaryModal.jsx
import { useEffect, useRef, useState } from "react";

const parseSummary = (rawSummary) => {
  if (!rawSummary) return null;

  const sections = {
    whatHappened: "",
    importantPoints: [],
    actionItems: [],
  };

  const whatHappenedMatch = rawSummary.match(
    /What Happened:\s*(.+?)(?=\n\nImportant Points:|$)/s
  );
  if (whatHappenedMatch) {
    sections.whatHappened = whatHappenedMatch[1].trim();
  }

  const importantMatch = rawSummary.match(
    /Important Points:\s*([\s\S]+?)(?=\n\nAction Items:|$)/
  );
  if (importantMatch) {
    sections.importantPoints = importantMatch[1]
      .split("\n")
      .map((line) => line.replace(/^[•\-\*]\s*/, "").trim())
      .filter(Boolean);
  }

  const actionMatch = rawSummary.match(/Action Items:\s*([\s\S]+?)$/);
  if (actionMatch) {
    sections.actionItems = actionMatch[1]
      .split("\n")
      .map((line) => line.replace(/^[•\-\*]\s*/, "").trim())
      .filter(Boolean);
  }

  return sections;
};

const AiSummaryModal = ({ isOpen, isLoading, summary, error, onClose }) => {
  const modalRef = useRef(null);
  const parsedSummary = summary ? parseSummary(summary) : null;
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape" && isOpen) onClose();
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  useEffect(() => {
    document.body.style.overflow = isOpen ? "hidden" : "";
    return () => { document.body.style.overflow = ""; };
  }, [isOpen]);

  const handleBackdropClick = (e) => {
    if (modalRef.current && !modalRef.current.contains(e.target)) {
      onClose();
    }
  };

  const handleCopy = async () => {
    if (!summary) return;
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard unavailable — silently ignore */
    }
  };

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ backgroundColor: "rgba(0,0,0,0.75)", backdropFilter: "blur(8px)" }}
      onClick={handleBackdropClick}
    >
      <div
        ref={modalRef}
        className="relative w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden"
        style={{
          animation: "modalIn 0.25s cubic-bezier(0.34,1.56,0.64,1) forwards",
          maxHeight: "88vh",
          background: "linear-gradient(180deg, #14141a 0%, #0d0d11 100%)",
          border: "1px solid rgba(168,85,247,0.18)",
          boxShadow: "0 0 0 1px rgba(255,255,255,0.03), 0 20px 60px -15px rgba(0,0,0,0.6), 0 0 40px -10px rgba(168,85,247,0.15)",
        }}
      >
        {/* Ambient glow */}
        <div
          className="pointer-events-none absolute -top-24 -right-16 w-56 h-56 rounded-full opacity-20 blur-3xl"
          style={{ background: "radial-gradient(circle, #a855f7 0%, transparent 70%)" }}
        />
        <div
          className="pointer-events-none absolute -bottom-24 -left-16 w-56 h-56 rounded-full opacity-10 blur-3xl"
          style={{ background: "radial-gradient(circle, #10b981 0%, transparent 70%)" }}
        />

        {/* Header */}
        <div className="relative flex items-center justify-between gap-3 px-4 sm:px-6 py-4 border-b border-white/10">
          <div className="flex items-center gap-3 min-w-0">
            <span
              className="shrink-0 w-9 h-9 rounded-xl flex items-center justify-center text-base"
              style={{
                background: "linear-gradient(135deg, rgba(168,85,247,0.25), rgba(16,185,129,0.2))",
                border: "1px solid rgba(168,85,247,0.3)",
                boxShadow: "0 0 16px -4px rgba(168,85,247,0.5)",
              }}
            >
              ✨
            </span>
            <div className="min-w-0">
              <h2 className="text-white font-semibold text-base leading-tight truncate">AI Summary</h2>
              <p className="text-[11px] text-gray-500 leading-tight mt-0.5 truncate">
                Conversation insights generated by AI
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close"
            className="shrink-0 w-8 h-8 flex items-center justify-center rounded-full text-gray-400 hover:text-white hover:bg-white/10 transition-all"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="relative overflow-y-auto" style={{ maxHeight: "calc(88vh - 68px)" }}>

          {/* Loading */}
          {isLoading && (
            <div className="flex flex-col items-center justify-center py-16 gap-4">
              <div className="relative w-14 h-14">
                <div
                  className="absolute inset-0 rounded-full"
                  style={{
                    background: "conic-gradient(from 0deg, #a855f7, #10b981, #a855f7)",
                    animation: "spin 1.1s linear infinite",
                    WebkitMask: "radial-gradient(farthest-side, transparent calc(100% - 3px), #000 calc(100% - 3px))",
                    mask: "radial-gradient(farthest-side, transparent calc(100% - 3px), #000 calc(100% - 3px))",
                  }}
                />
                <span className="absolute inset-0 flex items-center justify-center text-xl">✨</span>
              </div>
              <div className="text-center">
                <p className="text-white font-medium text-sm">Generating summary…</p>
                <p className="text-gray-500 text-xs mt-1">Analyzing your conversation with AI</p>
              </div>
            </div>
          )}

          {/* Error */}
          {!isLoading && error && (
            <div className="p-4 sm:p-6">
              <div className="flex items-start gap-3 p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                <span className="text-red-400 text-lg shrink-0">⚠️</span>
                <div className="min-w-0">
                  <p className="text-red-400 font-medium text-sm">Failed to generate summary</p>
                  <p className="text-red-400/70 text-xs mt-0.5 break-words">{error}</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="mt-4 w-full py-2.5 rounded-xl border border-white/10 text-gray-400 text-sm hover:bg-white/5 transition-colors"
              >
                Close
              </button>
            </div>
          )}

          {/* Summary */}
          {!isLoading && !error && parsedSummary && (
            <div className="p-4 sm:p-6 space-y-4">

              {/* What Happened */}
              {parsedSummary.whatHappened && (
                <div
                  className="rounded-xl px-4 py-3.5"
                  style={{
                    background: "linear-gradient(135deg, rgba(168,85,247,0.12), rgba(168,85,247,0.04))",
                    border: "1px solid rgba(168,85,247,0.22)",
                  }}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-purple-300 text-sm leading-none">✦</span>
                    <p className="text-[11px] font-semibold text-purple-300/90 uppercase tracking-widest">
                      What Happened
                    </p>
                  </div>
                  <p className="text-gray-200 text-sm leading-relaxed">
                    {parsedSummary.whatHappened}
                  </p>
                </div>
              )}

              {/* Important Points */}
              {parsedSummary.importantPoints.length > 0 && (
                <div
                  className="rounded-xl px-4 py-3.5"
                  style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <div className="flex items-center gap-2 mb-2.5">
                    <span className="text-amber-300 text-sm leading-none">💡</span>
                    <p className="text-[11px] font-semibold text-gray-400 uppercase tracking-widest">
                      Important Points
                    </p>
                  </div>
                  <ul className="space-y-2">
                    {parsedSummary.importantPoints.map((point, idx) => (
                      <li key={idx} className="flex items-start gap-2.5">
                        <span className="mt-[7px] shrink-0 w-1.5 h-1.5 rounded-full bg-purple-400" />
                        <span className="text-gray-300 text-sm leading-relaxed">{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Action Items */}
              {parsedSummary.actionItems.length > 0 && (
                <div
                  className="rounded-xl px-4 py-3.5"
                  style={{ background: "rgba(16,185,129,0.06)", border: "1px solid rgba(16,185,129,0.18)" }}
                >
                  <div className="flex items-center gap-2 mb-2.5">
                    <span className="text-emerald-400 text-sm leading-none">✓</span>
                    <p className="text-[11px] font-semibold text-emerald-300/90 uppercase tracking-widest">
                      Action Items
                    </p>
                  </div>
                  <ul className="space-y-2">
                    {parsedSummary.actionItems.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-2.5">
                        <span className="shrink-0 mt-0.5 w-4 h-4 rounded border-2 border-emerald-500/50 flex items-center justify-center">
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                        </span>
                        <span className="text-gray-300 text-sm leading-relaxed">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Fallback if parsing fails */}
              {!parsedSummary.whatHappened &&
                parsedSummary.importantPoints.length === 0 &&
                parsedSummary.actionItems.length === 0 && (
                  <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{summary}</p>
              )}

              {/* Copy + Footer */}
              <div className="pt-1 space-y-3">
                <button
                  onClick={handleCopy}
                  className="w-full inline-flex items-center justify-center gap-2 py-2.5 rounded-xl text-sm font-medium transition-all active:scale-[0.98]"
                  style={{
                    background: copied
                      ? "rgba(16,185,129,0.12)"
                      : "linear-gradient(135deg, rgba(168,85,247,0.14), rgba(16,185,129,0.1))",
                    border: copied ? "1px solid rgba(16,185,129,0.35)" : "1px solid rgba(168,85,247,0.25)",
                    color: copied ? "#6ee7b7" : "#e9d5ff",
                  }}
                >
                  {copied ? (
                    <>
                      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M20 6L9 17l-5-5" />
                      </svg>
                      Copied to clipboard
                    </>
                  ) : (
                    <>
                      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <rect x="9" y="9" width="13" height="13" rx="2" />
                        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                      </svg>
                      Copy Summary
                    </>
                  )}
                </button>

                <div className="pt-3 border-t border-white/10">
                  <p className="text-[11px] text-gray-600 text-center">
                    ✨ AI-generated · Not stored · Based on last 100 messages
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <style>{`
        @keyframes modalIn {
          from { opacity: 0; transform: translateY(20px) scale(0.96); }
          to   { opacity: 1; transform: translateY(0)    scale(1);    }
        }
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default AiSummaryModal;
